# Generated by Django 3.0.4 on 2020-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delagates', '0002_auto_20200318_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exibitor',
            name='InvoiceNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exibitor',
            name='ReceiptNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='InvoiceNum',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='ReceiptNum',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
