# Generated by Django 3.0.4 on 2020-03-23 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Delagates', '0003_auto_20200319_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='exibitor',
            name='Payment_Date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 6, 19, 57, 314611, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exibitor',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 23, 6, 20, 32, 234112, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paying',
            name='Payment_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 23, 6, 20, 55, 882298, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paying',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='Payment_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 23, 6, 23, 11, 192961, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
